sudo: required
services:
 - docker

language: generic

before_install:
 - docker build -t zarinfam/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true zarinfam/multi-docker-test npm test

after_success:
 - docker build -t zarinfam/multi-docker-client ./client
 - docker build -t zarinfam/multi-docker-nginx ./nginx
 - docker build -t zarinfam/multi-docker-server ./server
 - docker build -t zarinfam/multi-docker-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push zarinfam/multi-docker-client
 - docker push zarinfam/multi-docker-nginx
 - docker push zarinfam/multi-docker-server
 - docker push zarinfam/multi-docker-worker

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-886221772239"
 bucket_path: "multi-docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
